using UnityEngine;

public class FixCaveCollision : MonoBehaviour
{
    void Awake()
    {
        MeshCollider meshCollider = GetComponent<MeshCollider>();
        if (meshCollider == null || meshCollider.sharedMesh == null)
        {
            Debug.LogWarning("FixCaveCollision: No MeshCollider found on " + name);
            return;
        }

        // Create a reversed mesh for backface collision
        Mesh mesh = meshCollider.sharedMesh;
        Mesh invertedMesh = Instantiate(mesh); // Clone the mesh
        
        // Reverse triangle winding order
        int[] triangles = invertedMesh.triangles;
        for (int i = 0; i < triangles.Length; i += 3)
        {
            int temp = triangles[i];
            triangles[i] = triangles[i + 2];
            triangles[i + 2] = temp;
        }
        invertedMesh.triangles = triangles;

        // Create a child object to hold the backface collider
        GameObject backfaceObj = new GameObject("BackfaceCollider_AutoGenerated");
        backfaceObj.transform.SetParent(transform, false);
        backfaceObj.transform.localPosition = Vector3.zero;
        backfaceObj.transform.localRotation = Quaternion.identity;
        backfaceObj.transform.localScale = Vector3.one;

        MeshCollider backCollider = backfaceObj.AddComponent<MeshCollider>();
        backCollider.sharedMesh = invertedMesh;
    }
}
